### PR TITLE
Add Read to Memory function

### PR DESCRIPTION
**Pull request by BrutuZ**
Return a tuple with the file name and its content without extracting to disk.
As seen on pyUnRAR2 (https://code.google.com/p/py-unrar2/)

### CODE REVIEW

**Comment by davide-romanini** [comment]
No more work on this project? On PyPi there's still an old 0.2 version. Two forks implement in almost the same way (BrutuZ and Cubixmeister's) this open-in-memory functionality. I'd appreciate very much a new release, even a 0.3-beta could be fine.

**Comment by matiasb** [comment]
Ack, thanks for your comment. I didn't get the time to work on a new release, but will try to take a look soon and check how to merge these changes.

**Comment by davide-romanini** [comment]
Ok. For your information I tested the Cubixmeister's implementation and tested it with ~1500 rar compressed cbr files without any problem, both on standard x86 machine and a smaller armv5te NAS machine. I haven't any real benchmark but to me seems a bit faster than other solutions using unrar command in pipe. unrar lib version used for tests: 5.2.5. Didn't tested on windows.

**Comment by matiasb** [comment]
FYI, I got the feature implemented and committed to master branch (based on this pull request, thanks BrutuZ, and on Cubixmeister's work). If you can let me know if it works for you, that would be great. Will prepare a release in the next few days.
Thanks, and sorry for the delayed update (couldn't find the time to work on the tests and docs updates).

**Comment by davide-romanini** [comment]
Thanks, I made a quick test and it works fine.

**Comment by matiasb** [comment]
Changes implemented by #5, new version 0.3 released.
Thanks @BrutuZ, @davide-romanini.

**Pull request closed without merging**
